codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 80%

ignore:
  - '**/*.d.ts'
  - '**/*.config.*'
  - '**/types/**'
  - 'infra/**'
  - 'docs/**'
  - 'scripts/**'
