---
name: Terraform Apply

description: Terraform Apply

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true
  gcp-workload-identity-provider:
    description: GCP Workload Identity Provider (domain ディレクトリの場合に必要)
    required: false
  gcp-service-account:
    description: GCP Service Account (domain ディレクトリの場合に必要)
    required: false

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud (for domain directory)
      if: inputs.gcp-workload-identity-provider != '' && inputs.gcp-service-account != ''
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.gcp-workload-identity-provider }}
        service_account: ${{ inputs.gcp-service-account }}

    - name: Set contact_address_lines as JSON
      if: env.CONTACT_ADDRESS_LINES != ''
      run: |
        echo "TF_VAR_contact_address_lines=$(echo "$CONTACT_ADDRESS_LINES" | jq -R -c 'split(",")')" >> $GITHUB_ENV
      shell: bash

    - name: Terraform Apply
      run: |
        export CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN}"
        export TF_VAR_gcp_project_id="${GCP_PROJECT_ID}"
        export TF_VAR_cloudflare_api_token="${CLOUDFLARE_API_TOKEN}"
        export TF_VAR_cloudflare_account_id="${CLOUDFLARE_ACCOUNT_ID}"
        export TF_VAR_contact_country_code="${CONTACT_COUNTRY_CODE}"
        export TF_VAR_contact_postal_code="${CONTACT_POSTAL_CODE}"
        export TF_VAR_contact_administrative_area="${CONTACT_ADMINISTRATIVE_AREA}"
        export TF_VAR_contact_locality="${CONTACT_LOCALITY}"
        export TF_VAR_contact_recipient="${CONTACT_RECIPIENT}"
        export TF_VAR_contact_email="${CONTACT_EMAIL}"
        export TF_VAR_contact_phone="${CONTACT_PHONE}"
        export TF_VAR_yearly_price_currency="${YEARLY_PRICE_CURRENCY}"
        export TF_VAR_yearly_price_units="${YEARLY_PRICE_UNITS}"
        terraform apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      shell: bash
