---
name: Terraform Apply

description: Terraform Apply

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true
  gcp-workload-identity-provider:
    description: GCP Workload Identity Provider (domain ディレクトリの場合に必要)
    required: false
  gcp-service-account:
    description: GCP Service Account (domain ディレクトリの場合に必要)
    required: false

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud (for domain directory)
      if: inputs.gcp-workload-identity-provider != '' && inputs.gcp-service-account != ''
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.gcp-workload-identity-provider }}
        service_account: ${{ inputs.gcp-service-account }}

    - name: Terraform Apply
      run: |
        export TF_VAR_gcp_project_id="${GCP_PROJECT_ID}"
        export TF_VAR_neon_api_key="${NEON_API_KEY}"
        export TF_VAR_vercel_api_token="${VERCEL_API_TOKEN}"
        terraform apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      shell: bash
