name: '🐞 Bug Report'
description: Report a bug to help us improve xtrade.
labels: [bug]
title: '[Bug] '
body:
  - type: markdown
    attributes:
      value: |
        ## 🧭 Overview
        Please fill out the following information to help us understand and fix the issue.

        **Before submitting**, please search [existing issues](https://github.com/tqer39/xtrade/issues) to avoid duplicates.

        Tip: Use this format for the summary: "When I ____, I expected ____ but ____ happened instead."
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe what's happening.
      placeholder: 'Example: Card listing fails to save when submitting the form'
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select based on frequency and impact.
      options:
        - 🔴 Critical (Service unavailable)
        - 🟠 High (Major feature affected)
        - 🟡 Medium (Workaround available)
        - 🟢 Low (Minor issue)
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what should happen normally, including screen state and messages.
      placeholder: 'Example: Card listing should be saved and appear in my listings'
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happens. Include screenshots or logs if available.
      placeholder: 'Example: Form submission hangs and browser console shows an error'
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue. Screenshots or video links are helpful.
      placeholder: |
        1. Log in to xtrade
        2. Go to card listing page
        3. Fill in the form and click "Submit"
        4. Error appears
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: 'Example: Chrome 124, Safari 17.5, Firefox 128'
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: Operating System
      description: Select all operating systems where this issue occurs.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: Issue still occurs on the latest version
          required: true
        - label: Checked existing issues and discussions
          required: false
        - label: Attached relevant logs or screenshots
          required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Include related Pull Requests or investigation findings.
      placeholder: 'Example: Similar issue in #123'
