name: '🐞 バグ報告'
description: 不具合の詳細を報告して、迅速な解決につなげましょう。
labels: [bug]
title: '[Bug] '
body:
  - type: markdown
    attributes:
      value: |
        ## 🧭 概要
        問題の内容と影響範囲がひと目でわかるように、以下の項目を埋めてください。

        **報告前に** [既存の Issue](https://github.com/tqer39/xtrade/issues) を検索して、同じ問題が報告されていないか確認してください。

        ヒント: 「〜したとき、〜を期待したが、〜が起こった」の形式で概要を書くとわかりやすいです。
  - type: input
    id: summary
    attributes:
      label: バグの概要
      description: 何が起きているのかを一言で教えてください。
      placeholder: 例）カード出品フォームの送信時に保存されない
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: 影響度
      description: 発生頻度や影響範囲を踏まえて選択してください。
      options:
        - 🔴 クリティカル（利用不能）
        - 🟠 高（主要機能に支障）
        - 🟡 中（回避策あり）
        - 🟢 低（軽微な不具合）
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 本来期待する挙動
      description: 正常な場合にどう動くべきか、画面の状態やメッセージも含めて記載してください。
      placeholder: 例）カードが保存され、出品一覧に表示される
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の挙動
      description: 実際に何が起こっているのか、スクリーンショットやログがあれば添付してください。
      placeholder: 例）送信ボタンを押してもハングし、ブラウザコンソールにエラーが表示される
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 発生手順を番号付きで記載してください。スクリーンショットや動画リンクがあると助かります。
      placeholder: |
        1. xtrade にログイン
        2. カード出品ページに移動
        3. フォームを入力し「出品する」をクリック
        4. エラーが表示される
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: ブラウザ
      description: 使用しているブラウザを教えてください。
      placeholder: 例）Chrome 124, Safari 17.5, Firefox 128
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: オペレーティングシステム
      description: 問題が発生した OS を選択してください。
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  - type: checkboxes
    id: checks
    attributes:
      label: 事前確認
      options:
        - label: 最新版に更新しても問題が再現する
          required: true
        - label: 既存のIssue・ディスカッションを確認済み
          required: false
        - label: 関連するログやスクリーンショットを添付した
          required: false
  - type: textarea
    id: notes
    attributes:
      label: 備考・関連情報
      description: 関連するPull Requestや調査結果があれば記載してください。
      placeholder: 例）#123 に類似の問題があります
