name: '🚀 Feature Request'
description: Propose new features or improvements for xtrade.
labels: [enhancement]
title: '[Feature] '
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Desired Experience
        Share your idea and the value it would bring to users.

        **Before submitting**, please search [existing issues](https://github.com/tqer39/xtrade/issues) to check if this feature has already been requested.
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Summarize the feature or improvement in one sentence.
      placeholder: 'Example: Add price history chart for listed cards'
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: User Story
      description: 'Describe "who, why, and what" in the format: "As a [user type], I want [goal] because [reason]."'
      placeholder: 'Example: As a card collector, I want to see price trends at a glance because I want to make informed trading decisions.'
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Detailed Idea
      description: Provide specifics like screen mockups, scenarios, or required data. Diagrams and links are welcome.
      placeholder: 'Example: Display a line chart showing price history on the card detail page'
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Expected Priority
      options:
        - 🟥 ASAP (Needed for next release)
        - 🟧 High (1-2 sprints)
        - 🟨 Medium (When timing allows)
        - 🟩 Low (Sharing an idea)
      description: Add context in notes if needed.
    validations:
      required: true
  - type: textarea
    id: metrics
    attributes:
      label: Success Metrics
      description: How will we measure success? What user feedback should we look for?
      placeholder: 'Example: User engagement with card detail pages increases by 15%, positive user feedback'
  - type: textarea
    id: related
    attributes:
      label: Related Information
      description: Reference links, existing issues, or research materials.
      placeholder: 'Example: #256 (Price API), Figma mockup: https://...'
  - type: checkboxes
    id: collaboration
    attributes:
      label: Collaboration Interests
      description: Let us know if you can help with implementation or testing.
      options:
        - label: Can participate in specification and requirements definition
        - label: Can perform design review
        - label: Can contribute to implementation (code)
        - label: Can help with user testing
