name: '🚀 機能追加リクエスト'
description: 新しい体験や改善アイデアを提案しましょう。
labels: [enhancement]
title: '[Feature] '
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 目指す体験
        アイデアの背景や実現したい姿を共有してください。利用者にどんな価値を届けたいかがポイントです。

        **提案前に** [既存の Issue](https://github.com/tqer39/xtrade/issues) を検索して、同様のリクエストがないか確認してください。
  - type: input
    id: summary
    attributes:
      label: 提案の概要
      description: どのような機能・改善かを一文でまとめてください。
      placeholder: 例）出品カードの価格推移グラフを追加
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: ユーザーストーリー
      description: '「誰が・何のために・どうしたいか」を「〜として、〜したい。なぜなら〜だからだ。」の形式で記載してください。'
      placeholder: 例）カードコレクターとして、価格推移を一目で確認したい。なぜなら適切な売買判断をしたいからだ。
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 詳細アイデア
      description: 具体的な画面案、シナリオ、必要なデータなどを記載してください。図やリンクを添付しても構いません。
      placeholder: 例）カード詳細ページに価格履歴の折れ線グラフを表示する
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 期待する優先度
      options:
        - 🟥 ASAP（直近のリリースで必要）
        - 🟧 高（1〜2スプリント内に実現したい）
        - 🟨 中（タイミングが合えば進めたい）
        - 🟩 低（アイデアの共有段階）
      description: 背景の事情があれば備考に記載してください。
    validations:
      required: true
  - type: textarea
    id: metrics
    attributes:
      label: 成功指標・評価方法
      description: 実装後に効果を測る指標や、ユーザーからのフィードバック方法を教えてください。
      placeholder: 例）カード詳細ページの滞在時間が15%向上、ユーザーからのポジティブなフィードバック
  - type: textarea
    id: related
    attributes:
      label: 関連する情報
      description: 参考リンク、既存のIssue、調査資料などがあれば記載してください。
      placeholder: '例）#256（価格API）、Figmaモック: https://...'
  - type: checkboxes
    id: collaboration
    attributes:
      label: コラボレーション希望
      description: 実装や検証に協力できる内容があれば教えてください。
      options:
        - label: 仕様策定や要件定義に参加できる
        - label: デザインレビューを行える
        - label: 実装（コード）に貢献できる
        - label: ユーザーテストに協力できる
